# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 11:15
from __future__ import unicode_literals

import authentication.utilmodels
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_account_picture_mini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=authentication.utilmodels.MyImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='account',
            name='picture_mini',
            field=authentication.utilmodels.MyImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
